# declare anchor function &docker-defaults
docker-defaults: &docker-defaults
  docker:
    # docker file with docker-compose installed
    - image: quay.io/nyulibraries/circleci_docker:19.03.13-dc-1.27.4-0
  working_directory: ~/app


# declare anchor function &build_docker
build_docker: &build_docker
  run:
    name: Build docker image
    command: docker-compose build


# declare anchor function &push_to_quay
push_to_quay: &push_to_quay
  run:
    name: Push docker image to quay
    command: |
      docker login -u="$QUAY_USERNAME" -p="$QUAY_PASSWORD" quay.io
      docker push quay.io/ym26/simple-http:latest



version: 2.1
jobs:
  # actual job to run
  build-my-app:
    # alias that calls anchor &docker-defaults. (e.g function call)
    <<: *docker-defaults
    steps:
      # checks out github code
      - checkout
      # sets up docker daemon to run docker commands
      - setup_remote_docker
      # call build_docker function (e.g: &build_docker)
      - <<: *build_docker
      # call push_to_quay function (e.g: &push_to_quay)
      - <<: *push_to_quay


  

workflows:
  version: 2.1
  build:
    jobs:
      # name of the job to reference run
      - build-my-app
